name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest  # You can change the runner environment as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: 3.11  # Specify Python version 3.11

      - name: Install dependencies
        run: pip install -r src/requirements.txt  # Install dependencies from the src folder

      - name: Install flake8
        run: pip install flake8

      - name: Run Linter
        run: flake8 --ignore=E501 src  # Replace with your linter command and specify the target directory, e.g., pylint src, mypy src, etc.

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Update package lists and upgrade packages
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y

    - name: Remove conflicting packages
      run: |
        sudo apt-get remove -y moby-containerd containerd moby-runc runc

    - name: Install Docker
      run: |
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Verify Docker installation
      run: |
        docker version
        docker info

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Build and Push Docker Image
      run: |
        # Get the username and password from GitHub Secrets
        quayIoUsername="${{ secrets.DEV_BOT_USER }}"
        quayIoPassword="${{ secrets.DEV_BOT_PASS }}"

        # Define the Docker image name and tag
        dockerImageName="devbot"
        dockerImageTag="latest"

        # Build the Docker image
        docker build -t "$dockerImageName:$dockerImageTag" .

        # Log in to the quay.io container registry using stdin for password
        echo "$quayIoPassword" | docker login quay.io -u "$quayIoUsername" --password-stdin

        # Tag the Docker image with the quay.io repository
        quayIoRepository="quay.io/codefresh_sa/DevBot"
        docker tag "$dockerImageName:$dockerImageTag" "$quayIoRepository:$dockerImageTag"      

    - name: Login to Quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.DEV_BOT_USER }}
        password: ${{ secrets.DEV_BOT_PASS }}

    - name: Push to registry
      run: |    
        # Push the Docker image to the quay.io container registry
        docker push "$quayIoRepository:$dockerImageTag"

    - name: Clean Up
      run: |
        # Clean up: remove the local Docker image
        docker rmi "$dockerImageName:$dockerImageTag"
